name: Lint

on: [push, pull_request]

env:
  FORCE_COLOR: 1

permissions:
  contents: read

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
      - uses: actions/setup-python@v5
        with:
          python-version-file: "pyproject.toml"
          cache: pip
      - uses: tox-dev/action-pre-commit-uv@v1
